# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\new.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 724)
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/2540911/Pictures/aact-logo-5-colors-decade-outined.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 80, 771, 331))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setEnabled(True)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 751, 271))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_2.setEnabled(True)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout.addWidget(self.widget_2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 300, 751, 21))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_2.addWidget(self.label_19)
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_2.addWidget(self.label_18)
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_2.addWidget(self.label_17)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_2.addWidget(self.label_16)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 561, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 121, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(130, 20, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(250, 20, 111, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 40, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 121, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(410, 10, 47, 13))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(370, 30, 111, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(370, 50, 61, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(480, 30, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(480, 50, 111, 16))
        self.label_4.setObjectName("label_4")
        self.label_54 = QtWidgets.QLabel(self.groupBox_2)
        self.label_54.setGeometry(QtCore.QRect(255, 45, 101, 20))
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(580, 10, 411, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 81, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(220, 20, 101, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(220, 40, 111, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 40, 81, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(100, 20, 111, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(100, 40, 111, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(340, 20, 61, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(340, 40, 61, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 410, 981, 271))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(550, 20, 91, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.verticalLayout.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.verticalLayout.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_22.setObjectName("label_22")
        self.verticalLayout.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.verticalLayout.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_24.setObjectName("label_24")
        self.verticalLayout.addWidget(self.label_24)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(650, 20, 111, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_2.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_2.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_2.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_2.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_2.addWidget(self.label_29)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(550, 170, 91, 87))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_30 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_3.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_3.addWidget(self.label_31)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(650, 170, 111, 87))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_35 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_4.addWidget(self.label_35)
        self.label_34 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_4.addWidget(self.label_34)
        self.label_32 = QtWidgets.QLabel(self.groupBox_4)
        self.label_32.setGeometry(QtCore.QRect(780, 20, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox_4)
        self.label_33.setGeometry(QtCore.QRect(780, 50, 191, 31))
        self.label_33.setWordWrap(True)
        self.label_33.setObjectName("label_33")
        self.label_36 = QtWidgets.QLabel(self.groupBox_4)
        self.label_36.setGeometry(QtCore.QRect(780, 80, 191, 21))
        self.label_36.setObjectName("label_36")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton.setGeometry(QtCore.QRect(780, 130, 191, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_2.setGeometry(QtCore.QRect(780, 100, 191, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(780, 190, 91, 61))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_37 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_5.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_5.addWidget(self.label_38)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(880, 190, 91, 61))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_39 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_6.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_6.addWidget(self.label_40)
        self.label_53 = QtWidgets.QLabel(self.groupBox_4)
        self.label_53.setGeometry(QtCore.QRect(780, 170, 191, 16))
        self.label_53.setObjectName("label_53")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 531, 241))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3.addWidget(self.widget_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(780, 80, 211, 331))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 20, 91, 301))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_42 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_7.addWidget(self.label_42)
        self.label_41 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_7.addWidget(self.label_41)
        self.label_43 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_7.addWidget(self.label_43)
        self.label_44 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_7.addWidget(self.label_44)
        self.label_45 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_7.addWidget(self.label_45)
        self.label_46 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_7.addWidget(self.label_46)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(110, 20, 91, 301))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_47 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_8.addWidget(self.label_47)
        self.label_48 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_8.addWidget(self.label_48)
        self.label_49 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_8.addWidget(self.label_49)
        self.label_50 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_8.addWidget(self.label_50)
        self.label_51 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_8.addWidget(self.label_51)
        self.label_52 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_8.addWidget(self.label_52)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        self.menuCommands = QtWidgets.QMenu(self.menubar)
        self.menuCommands.setObjectName("menuCommands")
        self.menuDebug = QtWidgets.QMenu(self.menubar)
        self.menuDebug.setObjectName("menuDebug")
        self.menuHelp_About = QtWidgets.QMenu(self.menubar)
        self.menuHelp_About.setObjectName("menuHelp_About")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImmediately = QtWidgets.QAction(MainWindow)
        self.actionImmediately.setObjectName("actionImmediately")
        self.actionIn_1_minute = QtWidgets.QAction(MainWindow)
        self.actionIn_1_minute.setObjectName("actionIn_1_minute")
        self.actionIn_n_minutes = QtWidgets.QAction(MainWindow)
        self.actionIn_n_minutes.setObjectName("actionIn_n_minutes")
        self.actionOpen_in_Google_Sheets = QtWidgets.QAction(MainWindow)
        self.actionOpen_in_Google_Sheets.setObjectName("actionOpen_in_Google_Sheets")
        self.actionDisplay_All_Variables = QtWidgets.QAction(MainWindow)
        self.actionDisplay_All_Variables.setObjectName("actionDisplay_All_Variables")
        self.actionOpen_Log = QtWidgets.QAction(MainWindow)
        self.actionOpen_Log.setObjectName("actionOpen_Log")
        self.actionOpen_Log_2 = QtWidgets.QAction(MainWindow)
        self.actionOpen_Log_2.setEnabled(False)
        self.actionOpen_Log_2.setObjectName("actionOpen_Log_2")
        self.actionDisplay_All_Variables_2 = QtWidgets.QAction(MainWindow)
        self.actionDisplay_All_Variables_2.setEnabled(False)
        self.actionDisplay_All_Variables_2.setObjectName("actionDisplay_All_Variables_2")
        self.actionStandard = QtWidgets.QAction(MainWindow)
        self.actionStandard.setObjectName("actionStandard")
        self.actionWith_x_y_min_max = QtWidgets.QAction(MainWindow)
        self.actionWith_x_y_min_max.setObjectName("actionWith_x_y_min_max")
        self.actionOpen_Guidebook = QtWidgets.QAction(MainWindow)
        self.actionOpen_Guidebook.setObjectName("actionOpen_Guidebook")
        self.actionTelemetry_Guidebook = QtWidgets.QAction(MainWindow)
        self.actionTelemetry_Guidebook.setObjectName("actionTelemetry_Guidebook")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionChange_Read_Delay = QtWidgets.QAction(MainWindow)
        self.actionChange_Read_Delay.setObjectName("actionChange_Read_Delay")
        self.actionOpen_db = QtWidgets.QAction(MainWindow)
        self.actionOpen_db.setObjectName("actionOpen_db")
        self.actionOpen_Obstacle_Task_Table = QtWidgets.QAction(MainWindow)
        self.actionOpen_Obstacle_Task_Table.setObjectName("actionOpen_Obstacle_Task_Table")
        self.actionChange_Max_Graph_Values = QtWidgets.QAction(MainWindow)
        self.actionChange_Max_Graph_Values.setObjectName("actionChange_Max_Graph_Values")
        self.menuCommands.addAction(self.actionOpen_in_Google_Sheets)
        self.menuCommands.addAction(self.actionChange_Read_Delay)
        self.menuCommands.addAction(self.actionChange_Max_Graph_Values)
        self.menuCommands.addSeparator()
        self.menuCommands.addAction(self.actionOpen_db)
        self.menuDebug.addAction(self.actionOpen_Log_2)
        self.menuDebug.addAction(self.actionDisplay_All_Variables_2)
        self.menuHelp_About.addAction(self.actionOpen_Obstacle_Task_Table)
        self.menuHelp_About.addAction(self.actionOpen_Guidebook)
        self.menuHelp_About.addSeparator()
        self.menuHelp_About.addAction(self.actionTelemetry_Guidebook)
        self.menuHelp_About.addAction(self.actionAbout)
        self.menubar.addAction(self.menuCommands.menuAction())
        self.menubar.addAction(self.menuDebug.menuAction())
        self.menubar.addAction(self.menuHelp_About.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AACT Telemetry"))
        self.groupBox.setTitle(_translate("MainWindow", "DHT22: Humidity/Temperature"))
        self.label_19.setText(_translate("MainWindow", "Humidity:"))
        self.label_18.setText(_translate("MainWindow", "0.0%"))
        self.label_17.setText(_translate("MainWindow", "Temperature (C/F):"))
        self.label_16.setText(_translate("MainWindow", "0.0/32.0"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Begin Data Reading/Recording"))
        self.label.setText(_translate("MainWindow", "Begin from row:"))
        self.lineEdit.setText(_translate("MainWindow", "2"))
        self.pushButton_5.setText(_translate("MainWindow", "Start/Stop"))
        self.lineEdit_3.setText(_translate("MainWindow", "10"))
        self.label_3.setText(_translate("MainWindow", "Timeout (attempts):"))
        self.label_6.setText(_translate("MainWindow", "Status:"))
        self.label_7.setText(_translate("MainWindow", "Currently reading:"))
        self.label_8.setText(_translate("MainWindow", "Lag time:"))
        self.label_2.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "0s"))
        self.label_54.setText(_translate("MainWindow", "(Google Sheets)"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Debug Information"))
        self.label_5.setText(_translate("MainWindow", "len(queue) ="))
        self.label_9.setText(_translate("MainWindow", "failed_attempts ="))
        self.label_10.setText(_translate("MainWindow", "heal_attempts ="))
        self.label_11.setText(_translate("MainWindow", "last_read = "))
        self.label_12.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "0"))
        self.label_14.setText(_translate("MainWindow", "0"))
        self.label_15.setText(_translate("MainWindow", "0"))
        self.groupBox_4.setTitle(_translate("MainWindow", "NEO-6M: GPS"))
        self.label_20.setText(_translate("MainWindow", "Latitude:"))
        self.label_21.setText(_translate("MainWindow", "Longitude:"))
        self.label_22.setText(_translate("MainWindow", "Speed (MPH):"))
        self.label_23.setText(_translate("MainWindow", "Altitude (ft):"))
        self.label_24.setText(_translate("MainWindow", "Course (deg):"))
        self.label_25.setText(_translate("MainWindow", "0.000000"))
        self.label_26.setText(_translate("MainWindow", "0.000000"))
        self.label_27.setText(_translate("MainWindow", "0.00"))
        self.label_28.setText(_translate("MainWindow", "0.00"))
        self.label_29.setText(_translate("MainWindow", "0"))
        self.label_30.setText(_translate("MainWindow", "Attempting:"))
        self.label_31.setText(_translate("MainWindow", "Time elapsed:"))
        self.label_35.setText(_translate("MainWindow", "-"))
        self.label_34.setText(_translate("MainWindow", "0:00"))
        self.label_32.setText(_translate("MainWindow", "-"))
        self.label_33.setText(_translate("MainWindow", "-"))
        self.label_36.setText(_translate("MainWindow", "-"))
        self.pushButton.setText(_translate("MainWindow", "Open HERC Guidebook"))
        self.pushButton_2.setText(_translate("MainWindow", "Open Obstacle/Task Table"))
        self.label_37.setText(_translate("MainWindow", "Section"))
        self.label_38.setText(_translate("MainWindow", "Page"))
        self.label_39.setText(_translate("MainWindow", "-"))
        self.label_40.setText(_translate("MainWindow", "-"))
        self.label_53.setText(_translate("MainWindow", "HERC Guidebook Reference"))
        self.groupBox_5.setTitle(_translate("MainWindow", "MPU6050: Gyroscope (y/p/r only)"))
        self.label_42.setText(_translate("MainWindow", "Pitch"))
        self.label_41.setText(_translate("MainWindow", "Roll"))
        self.label_43.setText(_translate("MainWindow", "Yaw"))
        self.label_44.setText(_translate("MainWindow", "Pitch_avg_Δ"))
        self.label_45.setText(_translate("MainWindow", "Roll_avg_Δ"))
        self.label_46.setText(_translate("MainWindow", "Yaw_avg_Δ"))
        self.label_47.setText(_translate("MainWindow", "0"))
        self.label_48.setText(_translate("MainWindow", "0"))
        self.label_49.setText(_translate("MainWindow", "0"))
        self.label_50.setText(_translate("MainWindow", "0"))
        self.label_51.setText(_translate("MainWindow", "0"))
        self.label_52.setText(_translate("MainWindow", "0"))
        self.menuCommands.setTitle(_translate("MainWindow", "Commands"))
        self.menuDebug.setTitle(_translate("MainWindow", "Debug"))
        self.menuHelp_About.setTitle(_translate("MainWindow", "Help/About"))
        self.actionImmediately.setText(_translate("MainWindow", "Immediately"))
        self.actionIn_1_minute.setText(_translate("MainWindow", "In 1 minute"))
        self.actionIn_n_minutes.setText(_translate("MainWindow", "In n minutes"))
        self.actionOpen_in_Google_Sheets.setText(_translate("MainWindow", "Open in Google Sheets"))
        self.actionDisplay_All_Variables.setText(_translate("MainWindow", "Display All Variables"))
        self.actionOpen_Log.setText(_translate("MainWindow", "Open Log"))
        self.actionOpen_Log_2.setText(_translate("MainWindow", "Open Log"))
        self.actionDisplay_All_Variables_2.setText(_translate("MainWindow", "Display All Variables"))
        self.actionStandard.setText(_translate("MainWindow", "Standard"))
        self.actionWith_x_y_min_max.setText(_translate("MainWindow", "With x/y min/max"))
        self.actionOpen_Guidebook.setText(_translate("MainWindow", "Open HERC Guidebook"))
        self.actionTelemetry_Guidebook.setText(_translate("MainWindow", "Open Telemetry Guidebook"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
        self.actionChange_Read_Delay.setText(_translate("MainWindow", "Change Read Delay"))
        self.actionOpen_db.setText(_translate("MainWindow", "Open .db"))
        self.actionOpen_Obstacle_Task_Table.setText(_translate("MainWindow", "Open Obstacle/Task Table"))
        self.actionChange_Max_Graph_Values.setText(_translate("MainWindow", "Change Max Graph Values"))

